name: flutter_contentful
version: "0.2.4"
description: Contentful Delivery API client for Dart. This Dart package is a small abstraction on top of the Contentful Delivery API.
homepage: https://github.com/bennibau/flutter_contentful
repository: https://github.com/bennibau/flutter_contentful

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  equatable: ^1.2.3
  http: ^0.12.2
  json_annotation: ^3.0.1
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^1.9.0
  collection: ^1.14.13
  json_serializable: ^3.3.0
  test: ^1.15.3
